name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Run ShellCheck
      run: |
        shellcheck --version
        find . -name "*.sh" -exec shellcheck {} \;

  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bash ffmpeg jq
    
    - name: Check bash syntax
      run: |
        find . -name "*.sh" -exec bash -n {} \;
    
    - name: Test script help
      run: |
        chmod +x cvrt.sh
        ./cvrt.sh --help

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for trailing whitespace
      run: |
        find . -name "*.sh" -exec grep -l " $" {} \; | head -10
    
    - name: Check for missing newlines
      run: |
        find . -name "*.sh" -exec sh -c 'tail -c1 "$1" | read -r _ || echo "$1"' _ {} \; 